"""
Build an overview deck for the CHT-vs-Hankel-vs-1-sqrtx fit-comparison figures
(figures/<dataset>/fit_comparison/{wn}_{combined,panels}.png, generated by
scripts/save_fit_comparison_figures_graphene_*.py): a title slide, one section
title per sample, then one slide per wavenumber (combined.png on top, panels.png
below), for all 3 datasets. Font: Aptos throughout.

Run after scripts/save_fit_comparison_figures_graphene_{3x1_manual,4x1_lp1,4x1_lp2}.py.
"""
import os
from PIL import Image
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.ns import qn

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

FONT = 'Aptos'
NAVY = RGBColor(0x1E, 0x27, 0x61)
ICE = RGBColor(0xCA, 0xDC, 0xFC)
TEAL = RGBColor(0x1C, 0x72, 0x93)
MUTED = RGBColor(0x47, 0x55, 0x69)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)

SLIDE_W, SLIDE_H = Inches(13.333), Inches(7.5)
OUT_PPTX = 'slides/GMG_fit_comparison_overview.pptx'

wns = [1000, 991, 980, 970, 960, 950, 941, 930, 920, 911, 900, 890, 880, 870, 860]

# (section title, fit_comparison dir, slide-subtitle label)
DATASETS = [
    ('graphene_3x1_manual', 'figures/graphene_3x1_manual/fit_comparison', 'Gr/SiO₂/Si'),
    ('graphene_4x1_lp1 (edge)', 'figures/graphene_4x1_manual/lp1/fit_comparison', 'MoO₃(4.2nm)/Gr/SiO₂/Si — edge (lp1)'),
    ('graphene_4x1_lp2 (interior)', 'figures/graphene_4x1_manual/lp2/fit_comparison', 'MoO₃(4.2nm)/Gr/SiO₂/Si — interior (lp2)'),
]


def img_size_in(path):
    return Image.open(path).size


def no_autofit(tf):
    bodyPr = tf._txBody.find(qn('a:bodyPr'))
    for tag in ('a:normAutofit', 'a:spAutoFit'):
        el = bodyPr.find(qn(tag))
        if el is not None:
            bodyPr.remove(el)
    bodyPr.append(bodyPr.makeelement(qn('a:noAutofit'), {}))


def add_text(slide, x, y, w, h, text, size, color, bold=False, align=PP_ALIGN.LEFT,
             italic=False, font=FONT, anchor=MSO_ANCHOR.TOP):
    box = slide.shapes.add_textbox(x, y, w, h)
    tf = box.text_frame
    tf.word_wrap = True
    no_autofit(tf)
    tf.vertical_anchor = anchor
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.color.rgb = color
    run.font.bold = bold
    run.font.italic = italic
    run.font.name = font
    return box


prs = Presentation()
prs.slide_width = SLIDE_W
prs.slide_height = SLIDE_H
blank = prs.slide_layouts[6]

# ---------------------------------------------------------------- title slide
s = prs.slides.add_slide(blank)
bg = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, SLIDE_W, SLIDE_H)
bg.fill.solid(); bg.fill.fore_color.rgb = NAVY
bg.line.fill.background()
bg.shadow.inherit = False

for cx, cy, d, col in [(11.6, -0.9, 4.2, TEAL), (-1.2, 6.6, 3.6, TEAL)]:
    c = s.shapes.add_shape(MSO_SHAPE.OVAL, Inches(cx), Inches(cy), Inches(d), Inches(d))
    c.fill.solid(); c.fill.fore_color.rgb = col
    c.fill.transparency = 0
    c.line.fill.background()
    c.shadow.inherit = False
    sp = c.fill.fore_color._xFill
    alpha = sp.makeelement(qn('a:alpha'), {'val': '18000'})
    srgb = sp.find(qn('a:srgbClr'))
    srgb.append(alpha)

add_text(s, Inches(0.9), Inches(2.55), Inches(11.5), Inches(1.5),
         "GMG Fit Comparison Overview", 40, WHITE, bold=True, font=FONT)
add_text(s, Inches(0.9), Inches(3.55), Inches(11.5), Inches(0.7),
         "CHT vs. Hankel vs. 1/√x — all three fits overlaid on data, per wavenumber", 18, ICE, font=FONT)
add_text(s, Inches(0.9), Inches(4.95), Inches(11.5), Inches(0.5),
         "860–1000 cm⁻¹  ·  3 samples · 15 wavenumbers each  ·  "
         "combined overlay + a/b/c/d panel breakdown per wn", 13, ICE, italic=True, font=FONT)

margin = Inches(0.5)
content_w = SLIDE_W - 2 * margin

# ---------------------------------------------------------------- per-dataset sections
for section_title, fit_dir, subtitle in DATASETS:
    # section divider slide
    s = prs.slides.add_slide(blank)
    bg = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, SLIDE_W, SLIDE_H)
    bg.fill.solid(); bg.fill.fore_color.rgb = NAVY
    bg.line.fill.background()
    bg.shadow.inherit = False
    add_text(s, Inches(0.9), Inches(3.1), Inches(11.5), Inches(1.2),
              section_title, 34, WHITE, bold=True, font=FONT)
    add_text(s, Inches(0.9), Inches(4.05), Inches(11.5), Inches(0.6), subtitle, 16, ICE, font=FONT)

    for wn in wns:
        combined_path = f"{fit_dir}/{wn}cm-1_combined.png"
        panels_path = f"{fit_dir}/{wn}cm-1_panels.png"
        if not (os.path.exists(combined_path) and os.path.exists(panels_path)):
            print(f"Skipping {wn}cm-1 ({section_title}): missing figure(s)")
            continue

        s = prs.slides.add_slide(blank)
        s.background.fill.solid(); s.background.fill.fore_color.rgb = WHITE

        add_text(s, margin, Inches(0.22), content_w, Inches(0.5),
                  f"{wn} cm⁻¹", 26, NAVY, bold=True, font=FONT)
        add_text(s, margin, Inches(0.68), content_w, Inches(0.35), subtitle, 13, MUTED, font=FONT)

        # combined.png: centered, height-first sizing. top_h is capped so that
        # top_y + top_h + gap + bottom_h (fixed by panels.png's own aspect ratio
        # at full content_w) never exceeds the slide -- verified by the shape
        # bounds self-check below, don't just eyeball this.
        top_y = Inches(1.05)
        gap = Inches(0.1)
        pw2, ph2 = img_size_in(panels_path)
        bottom_h = Emu(int(content_w * ph2 / pw2))
        top_h = SLIDE_H - top_y - gap - bottom_h - Inches(0.1)  # 0.1in bottom margin
        pw, ph = img_size_in(combined_path)
        top_w = Emu(int(top_h * pw / ph))
        top_x = Emu(int((SLIDE_W - top_w) / 2))
        s.shapes.add_picture(combined_path, top_x, top_y, width=top_w, height=top_h)

        # panels.png: full content width below (bottom_h already computed above)
        bottom_y = top_y + top_h + gap
        s.shapes.add_picture(panels_path, margin, bottom_y, width=content_w, height=bottom_h)

prs.save(OUT_PPTX)
print(f"Saved {OUT_PPTX}")
